### ISSUE TITLE
TinyRDM_Setup_1.1.2_windows_amd64 杀毒软件报毒。

### ISSUE THREAD

**Issue by AdminQQZ** [tiny-craft/tiny-rdm#107] opened 2023-12-25 08:38 UTC
**Tiny RDM Version**
What version of Tiny RDM are you using?

**OS Version**
Which OS and version you launch? (Mac/Windows/Linux)

**Redis Version**
Which version of Redis are you using?

**Describe the bug**

Steps to Reproduce:

1.
2.

**Comment by tiny-craft** [comment] 2023-12-25 10:22
Duplicate of #48 
这个目前暂时没办法, 如果不放心可以先代码自己编译运行

**Closed** 2024-03-21 02:29 UTC
